[tool.ruff]
line-length = 100
target-version = "py314"
preview = true
exclude = [
    ".git",
    "venv",
    "misc/primes.py",
    "withgoogle/",
    "solver/sly",
    "solver/ply",
    "solver/equation_parser.py",
    "**/*_old.py"
    # ... more exclusions
]


[tool.ruff.lint]
# Enable all rules (or a specific set) and ignore certain ones
select = ["E", "W", "F", "UP", "NPY"]  # add "I"
ignore = ["E501",
          "E701",
          "UP015",
          "UP037",
         ]
preview = true

