[tool.ruff]
line-length = 90
target-version = "py314"
preview = true
exclude = [
    ".git",
    "venv",
    "misc/primes.py",
    "withgoogle/",
    "solver/sly",
    "solver/ply",
    "solver/equation_parser.py",
    "**/*_old.py"
    # ... more exclusions
]


[tool.ruff.lint]
# Enable all rules (or a specific set) and ignore certain ones
select = [
    "F",        # Pyflakes rules
    "W",        # PyCodeStyle warnings
    "E",        # PyCodeStyle errors
    "I",                   # Sort imports properly
    "UP",       # Warn if certain things can changed due to newer Python versions
    "C4",       # Catch incorrect use of comprehensions, dict, list, etc
    "FA",       # Enforce from __future__ import annotations
    "ISC",      # Good use of string concatenation
    "ICN",      # Use common import conventions
    "RET",      # Good return practices
    "SIM",      # Common simplification rules
    "TID",      # Some good import practices
    "PTH",      # Use pathlib instead of os.path
    "TD",            # Be diligent with TODO comments
    "NPY",      # Some numpy-specific things
]

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true
docstring-code-format = true

